version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    profiles:
      - all
      - db
  app:
    build:
      context: .
      args:
        NEXTCLOUD_VERSION: 28.0.0
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud-data:/var/www/html/data
      - nextcloud-config:/var/www/html/config
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-themes:/var/www/html/themes
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    depends_on:
      - db
    profiles:
      - all
  cron:
    build:
      context: .
      args:
        NEXTCLOUD_VERSION: 28.0.0
    restart: always
    volumes:
      - nextcloud-data:/var/www/html/data
      - nextcloud-config:/var/www/html/config
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-themes:/var/www/html/themes
    entrypoint: /cron.sh
    depends_on:
      - db
    profiles:
      - all
volumes:
  db:
  nextcloud-data:
  nextcloud-config:
  nextcloud-apps:
  nextcloud-themes: